version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: actix
      POSTGRES_PASSWORD: actix
      POSTGRES_DB: todo
    ports:
      - 5432:5432